# -*- coding: utf-8 -*-
"""Classes-ProjetoIntegrado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8r6Kn3wwW_RwzMToxnp19j_ezyS4T6g
"""

from abc import ABC, abstractmethod


# Kelvin Sammer
class Usuario(ABC): #Superclasse abstrata
    def __init__(self, nome: str, email: str):
        self.__nome = nome
        self.__email = email

    @property
    def nome(self): #Get Nome
        return self.__nome

    @property
    def email(self): #Get Email
        return self.__email

class Admin(Usuario): #Classe filho Admin
    def __init__(self, nome: str, email: str, senha: str):
        super().__init__(nome, email)
        self.__senha = senha

class Professor(Usuario): #Classe filho Professor
    def __init__(self, nome: str, email: str, senha: str, materia: str, turma: str):
        super().__init__(nome, email)
        self.__senha = senha
        self.__materia = materia
        self.__turma = turma

    @property
    def materia(self): #Get Materia
        return self.__materia

    @property
    def turma(self): #Get Turma
        return self.__turma

class Responsavel(Usuario): #Classe filho Responsável
    def __init__(self, nome: str, email: str, senha: str, matriculaAluno: int, dataNascimento: str, endereco: str):
        super().__init__(nome, email)
        self.__senha = senha
        self.__matriculaAluno = matriculaAluno
        self.__dataNascimento = dataNascimento
        self.__endereco = endereco

    @property
    def matriculaAluno(self): #Get Matrícula
        return self.__matriculaAluno


    @property
    def dataNascimento(self): #Get Data de nascimento
        return self.__dataNascimento

    @property
    def endereco(self): #Get Endereço
        return self.__endereco

    @endereco.setter
    def endereco(self, novoEndereco): #Set novo Endereço
        self.__endereco = novoEndereco


# Jonathan Oliveira
from typing import Optional

class Turma:
    def __init__(self, id_turma: int, nome_turma: str, ano_letivo: int):
        self.__id_turma = id_turma
        self.__nome_turma = nome_turma
        self.__ano_letivo = ano_letivo
        self.__professor_responsavel: Optional[Professor] = None

    @property
    def nome_turma(self):
        return self.__nome_turma

    @nome_turma.setter
    def nome_turma(self, novo_nome):
        self.__nome_turma = novo_nome
    
    @property
    def professor(self):
        return self.__professor_responsavel

    def definir_professor(self, professor: Professor):
        self.__professor_responsavel = professor

    # Keven

    # CLASSE Disciplina
    class Disciplina:
        def __init__(self, codigo, nome, carga_horaria, professor):
            self.codigo = codigo
            self.nome = nome
            self.carga_horaria = carga_horaria
            self.professor = professor
        
        # Dicionário que armazena notas dos alunos
        # chave = aluno_id | valor = lista de notas
            self.alunos_notas = {}
       
        def adicionar_nota(self, aluno_id, nota):
        # Se o aluno ainda não existir no dicionário, cria a lista 
            if aluno_id not in self.alunos_notas:
                self.alunos_notas[aluno_id] = []
                self.alunos_notas[aluno_id].append(nota)
        # Retorna mensagem de confirmação   
                return f"✅ Nota {nota} adicionada em {self.nome}"
        
        def media_aluno(self, aluno_id):
            notas = self.alunos_notas.get(aluno_id, [])
            if len(notas) == 0:
                return 0
            return sum(notas) / len(notas)

#Wellington 
class Aluno(Usuario):
    def __init__(self, nome: str, email: str, matricula: int, dataNascimento: str, turma: Turma):
        super().__init__(nome, email)
        self.__matricula = matricula
        self.__dataNascimento = dataNascimento
        self.__turma = turma
        self.__disciplinas = []

    def matricula(self):
        return self.__matricula
    
    def dataNascimento(self):
        return self.__dataNascimento

    def turma(self):
        return self.__turma

    def disciplinas(self):
        return self.__disciplinas

    def matricular_disciplina(self, disciplina):
        self.__disciplinas.append(disciplina)

# Rafael Paixão

# CLASSE Evento
from datetime import date  # importa o tipo date para o atributo de data


class Evento:  # organiza e gerencia os eventos escolares
    def __init__(self, título: str, data_evento: data, descricao: str, local: str, pais_responsaveis: str):
        self.__titulo = titulo
        self.__data_evento = data_evento
        self.__descrição = descricao
        self.__local = local
        self.__descricao = descricao
        self.__pais_responsaveis = pais_responsaveis

    @property  # retorna o título do evento
    def titulo_evento(self):
        return self.__titulo_evento

    @property  # retorna o dia do evento
    def data_evento(self):
        return self.__data_evento

    @property
    def descricao(self):  # retorna detalhadamente o evento
        return self.__descricao

    @property  # retorna o local onde o evento ocorrerá
    def local(self):
        return self.__local

    @property  # retorna a quem se destina o evento
    def publico_alvo(self):
        return self.__publico_alvo

    @descricao.setter  # possibilita editar a descrição do evento
    def descricao(self, nova_descricao: str):
        self.__descricao = nova_descricao

    @publico_alvo.setter  # possibilita editar o público alvo do evento
    def publico_alvo(self, novo_publico_alvo: str):
        self.__novo_publico_alvo = novo_publico_alvo
