# -*- coding: utf-8 -*-
"""Classes-ProjetoIntegrado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8r6Kn3wwW_RwzMToxnp19j_ezyS4T6g
"""

from abc import ABC, abstractmethod


# Kelvin Sammer
class Usuario(ABC): #Superclasse abstrata
    def __init__(self, nome: str, email: str):
        self.__nome = nome
        self.__email = email

    @property
    def nome(self): #Get Nome
        return self.__nome

    @property
    def email(self): #Get Email
        return self.__email

class Admin(Usuario): #Classe filho Admin
    def __init__(self, nome: str, email: str, senha: str):
        super().__init__(nome, email)
        self.__senha = senha

class Professor(Usuario): #Classe filho Professor
    def __init__(self, nome: str, email: str, senha: str, materia: str, turma: str):
        super().__init__(nome, email)
        self.__senha = senha
        self.__materia = materia
        self.__turma = turma

    @property
    def materia(self): #Get Materia
        return self.__materia

    @property
    def turma(self): #Get Turma
        return self.__turma

class Responsavel(Usuario): #Classe filho Responsável
    def __init__(self, nome: str, email: str, senha: str, matriculaAluno: int, dataNascimento: str, endereco: str):
        super().__init__(nome, email)
        self.__senha = senha
        self.__matriculaAluno = matriculaAluno
        self.__dataNascimento = dataNascimento
        self.__endereco = endereco

    @property
    def matriculaAluno(self): #Get Matrícula
        return self.__matriculaAluno


    @property
    def dataNascimento(self): #Get Data de nascimento
        return self.__dataNascimento

    @property
    def endereco(self): #Get Endereço
        return self.__endereco

    @endereco.setter
    def endereco(self, novoEndereco): #Set novo Endereço
        self.__endereco = novoEndereco


# Jonathan Oliveira
from typing import Optional

class Turma:
    def __init__(self, id_turma: int, nome_turma: str, ano_letivo: int):
        self.__id_turma = id_turma
        self.__nome_turma = nome_turma
        self.__ano_letivo = ano_letivo
        self.__professor_responsavel: Optional[Professor] = None

    @property
    def nome_turma(self):
        return self.__nome_turma

    @nome_turma.setter
    def nome_turma(self, novo_nome):
        self.__nome_turma = novo_nome
    
    @property
    def professor(self):
        return self.__professor_responsavel

    def definir_professor(self, professor: Professor):
        self.__professor_responsavel = professor
    
    # Métodos para matricular aluno, adicionar disciplina e tarefa depois que os outros implementarem suas classes...
