{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyO/Y4R2JHRDb3ZT4W/uNvVA",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/sammerk23/PAEP-Caucaia/blob/main/Nota.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "KoIhafdqOntC",
        "outputId": "01605fb7-4599-4c1f-ac3b-972e20f7fdef"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "✓ Disciplina Matemática adicionada\n",
            "✓ Disciplina Português adicionada\n",
            "✓ Aluno João Silva matriculado\n",
            "✓ Aluno Maria Oliveira matriculado\n",
            "🚀 MVP iniciado com sucesso!\n",
            "\n",
            "🎯 PAINEL GRADE CURRICULAR\n",
            "1 - Ver Grade da Turma\n",
            "2 - Lançar Nota\n",
            "3 - Ver Boletim do Aluno\n",
            "0 - Sair\n"
          ]
        }
      ],
      "source": [
        "\n",
        "\n",
        "# =====================================================\n",
        "# MVP Grade Curricular - Painel Acompanhamento Escolar\n",
        "# UFCA | Sprint 1 PAEP Caucaia\n",
        "# =====================================================\n",
        "\n",
        "\n",
        "# -------------------------------\n",
        "# CLASSE DISCIPLINA\n",
        "# -------------------------------\n",
        "class Disciplina:\n",
        "    \"\"\"\n",
        "    Classe responsável por gerenciar:\n",
        "    - Dados da disciplina\n",
        "    - Notas dos alunos\n",
        "    - Cálculo de médias\n",
        "    \"\"\"\n",
        "\n",
        "    def __init__(self, codigo, nome, carga_horaria, professor):\n",
        "        # Código único da disciplina (ex: MAT001)\n",
        "        self.codigo = codigo\n",
        "\n",
        "        # Nome da disciplina (ex: Matemática)\n",
        "        self.nome = nome\n",
        "\n",
        "        # Carga horária semanal da disciplina\n",
        "        self.carga_horaria = carga_horaria\n",
        "\n",
        "        # Professor responsável pela disciplina\n",
        "        self.professor = professor\n",
        "\n",
        "        # Dicionário que armazena notas dos alunos\n",
        "        # chave = aluno_id | valor = lista de notas\n",
        "        self.alunos_notas = {}\n",
        "\n",
        "    def adicionar_nota(self, aluno_id, nota):\n",
        "        \"\"\"\n",
        "        Adiciona uma nota para um aluno específico\n",
        "        \"\"\"\n",
        "\n",
        "        # Se o aluno ainda não existir no dicionário, cria a lista\n",
        "        if aluno_id not in self.alunos_notas:\n",
        "            self.alunos_notas[aluno_id] = []\n",
        "\n",
        "        # Adiciona a nota na lista do aluno\n",
        "        self.alunos_notas[aluno_id].append(nota)\n",
        "\n",
        "        # Retorna mensagem de confirmação\n",
        "        return f\"✅ Nota {nota} adicionada em {self.nome}\"\n",
        "\n",
        "    def media_aluno(self, aluno_id):\n",
        "        \"\"\"\n",
        "        Calcula a média simples das notas do aluno\n",
        "        \"\"\"\n",
        "\n",
        "        # Obtém as notas do aluno (ou lista vazia)\n",
        "        notas = self.alunos_notas.get(aluno_id, [])\n",
        "\n",
        "        # Se o aluno não tiver notas, retorna 0\n",
        "        if len(notas) == 0:\n",
        "            return 0\n",
        "\n",
        "        # Calcula a média aritmética\n",
        "        return sum(notas) / len(notas)\n",
        "\n",
        "\n",
        "# -------------------------------\n",
        "# CLASSE TURMA\n",
        "# -------------------------------\n",
        "class Turma:\n",
        "    \"\"\"\n",
        "    Classe que representa uma turma escolar\n",
        "    \"\"\"\n",
        "\n",
        "    def __init__(self, nome, serie):\n",
        "        # Nome da turma (ex: 1ºA)\n",
        "        self.nome = nome\n",
        "\n",
        "        # Série/Ano escolar\n",
        "        self.serie = serie\n",
        "\n",
        "        # Lista de disciplinas da turma\n",
        "        self.disciplinas = []\n",
        "\n",
        "        # Lista de alunos matriculados\n",
        "        # Cada aluno é um dicionário com id e nome\n",
        "        self.alunos = []\n",
        "\n",
        "    def adicionar_disciplina(self, disciplina):\n",
        "        \"\"\"\n",
        "        Adiciona uma disciplina à turma\n",
        "        \"\"\"\n",
        "\n",
        "        # Insere a disciplina na lista\n",
        "        self.disciplinas.append(disciplina)\n",
        "\n",
        "        # Exibe confirmação no terminal\n",
        "        print(f\"✓ Disciplina {disciplina.nome} adicionada\")\n",
        "\n",
        "    def matricular_aluno(self, aluno_id, aluno_nome):\n",
        "        \"\"\"\n",
        "        Matricula um aluno na turma\n",
        "        \"\"\"\n",
        "\n",
        "        # Adiciona aluno na lista de alunos\n",
        "        self.alunos.append({\"id\": aluno_id, \"nome\": aluno_nome})\n",
        "\n",
        "        # Inicializa lista de notas vazia em todas disciplinas\n",
        "        for disc in self.disciplinas:\n",
        "            disc.alunos_notas[aluno_id] = []\n",
        "\n",
        "        # Confirmação no terminal\n",
        "        print(f\"✓ Aluno {aluno_nome} matriculado\")\n",
        "\n",
        "\n",
        "# -------------------------------\n",
        "# CLASSE GRADE CURRICULAR\n",
        "# -------------------------------\n",
        "class GradeCurricular:\n",
        "    \"\"\"\n",
        "    Classe principal do sistema\n",
        "    Responsável por gerenciar todas as turmas\n",
        "    \"\"\"\n",
        "\n",
        "    def __init__(self):\n",
        "        # Lista que armazena todas as turmas\n",
        "        self.turmas = []\n",
        "\n",
        "    def criar_turma(self, nome, serie):\n",
        "        \"\"\"\n",
        "        Cria e registra uma nova turma\n",
        "        \"\"\"\n",
        "\n",
        "        # Cria o objeto turma\n",
        "        turma = Turma(nome, serie)\n",
        "\n",
        "        # Adiciona a turma ao sistema\n",
        "        self.turmas.append(turma)\n",
        "\n",
        "        # Retorna a turma criada\n",
        "        return turma\n",
        "\n",
        "    def listar_grade(self, turma_nome):\n",
        "        \"\"\"\n",
        "        Exibe a grade curricular de uma turma\n",
        "        \"\"\"\n",
        "\n",
        "        # Procura a turma pelo nome\n",
        "        turma = next((t for t in self.turmas if t.nome == turma_nome), None)\n",
        "\n",
        "        # Caso não encontre a turma\n",
        "        if turma is None:\n",
        "            return \"❌ Turma não encontrada\"\n",
        "\n",
        "        # Monta texto da grade curricular\n",
        "        texto = f\"\\n📚 GRADE - {turma.nome} ({turma.serie})\\n\"\n",
        "\n",
        "        # Percorre disciplinas e adiciona ao texto\n",
        "        for i, disc in enumerate(turma.disciplinas, start=1):\n",
        "            texto += f\"{i}. {disc.nome} | Prof: {disc.professor}\\n\"\n",
        "\n",
        "        # Retorna o relatório final\n",
        "        return texto\n",
        "\n",
        "\n",
        "# =====================================================\n",
        "# CRIAÇÃO DO SISTEMA E DADOS DE EXEMPLO\n",
        "# =====================================================\n",
        "\n",
        "# Cria o sistema principal\n",
        "sistema = GradeCurricular()\n",
        "\n",
        "# Cria uma turma\n",
        "turma1a = sistema.criar_turma(\"1ºA\", \"1º Ano Fundamental\")\n",
        "\n",
        "# Adiciona disciplinas à turma\n",
        "turma1a.adicionar_disciplina(Disciplina(\"MAT001\", \"Matemática\", 4, \"Maria Silva\"))\n",
        "turma1a.adicionar_disciplina(Disciplina(\"POR001\", \"Português\", 5, \"João Santos\"))\n",
        "\n",
        "# Matricula alunos\n",
        "turma1a.matricular_aluno(101, \"João Silva\")\n",
        "turma1a.matricular_aluno(102, \"Maria Oliveira\")\n",
        "\n",
        "# Lançamento inicial de notas\n",
        "turma1a.disciplinas[0].adicionar_nota(101, 8.5)\n",
        "turma1a.disciplinas[0].adicionar_nota(102, 9.2)\n",
        "turma1a.disciplinas[1].adicionar_nota(101, 7.8)\n",
        "\n",
        "print(\"🚀 MVP iniciado com sucesso!\")\n",
        "\n",
        "\n",
        "# =====================================================\n",
        "# MENU INTERATIVO\n",
        "# =====================================================\n",
        "def menu():\n",
        "    \"\"\"\n",
        "    Exibe menu de opções do sistema\n",
        "    \"\"\"\n",
        "    print(\"\\n🎯 PAINEL GRADE CURRICULAR\")\n",
        "    print(\"1 - Ver Grade da Turma\")\n",
        "    print(\"2 - Lançar Nota\")\n",
        "    print(\"3 - Ver Boletim do Aluno\")\n",
        "    print(\"0 - Sair\")\n",
        "\n",
        "    # Retorna a opção escolhida pelo usuário\n",
        "    return input(\"Escolha: \")\n",
        "\n",
        "\n",
        "# Loop principal do sistema\n",
        "while True:\n",
        "    opcao = menu()\n",
        "\n",
        "    # Encerrar sistema\n",
        "    if opcao == \"0\":\n",
        "        print(\"👋 Sistema encerrado\")\n",
        "        break\n",
        "\n",
        "    # Listar grade curricular\n",
        "    elif opcao == \"1\":\n",
        "        print(sistema.listar_grade(\"1ºA\"))\n",
        "\n",
        "    # Lançar nova nota\n",
        "    elif opcao == \"2\":\n",
        "        aluno = int(input(\"ID do aluno: \"))\n",
        "\n",
        "        # Mostra opções de disciplinas\n",
        "        print(\"1 - Matemática\")\n",
        "        print(\"2 - Português\")\n",
        "\n",
        "        disc = int(input(\"Disciplina: \")) - 1\n",
        "        nota = float(input(\"Nota: \"))\n",
        "\n",
        "        print(turma1a.disciplinas[disc].adicionar_nota(aluno, nota))\n",
        "\n",
        "    # Exibir boletim\n",
        "    elif opcao == \"3\":\n",
        "        aluno = int(input(\"ID do aluno: \"))\n",
        "\n",
        "        print(f\"\\n📋 BOLETIM DO ALUNO {aluno}\")\n",
        "        for disc in turma1a.disciplinas:\n",
        "            media = disc.media_aluno(aluno)\n",
        "            print(f\"{disc.nome}: {media:.1f}\")\n",
        "\n",
        "    # Opção inválida\n",
        "    else:\n",
        "        print(\"❌ Opção inválida\")"
      ]
    }
  ]
}